<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}
$fields = array(
  array(
    'uid' => 'before_woo_announcements',
    'label' => 'Before Woo Announcements',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_woo_announcements',
    'label' => 'After Woo Announcements',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_billing_information',
    'label' => 'Before Billing Information',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_billing_information',
    'label' => 'After Billing Information',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_shipping_information',
    'label' => 'Before Shipping Information',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_shipping_information',
    'label' => 'After Shipping Information',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_notes',
    'label' => 'After Order Notes',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_customer_details',
    'label' => 'After Customer Details',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_order_review',
    'label' => 'Before Order Review',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_cart_contents',
    'label' => 'Before Cart Contents',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_cart_contents',
    'label' => 'After Cart Contents',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_order_shipping_contents',
    'label' => 'Before Order Shipping',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_shipping_contents',
    'label' => 'After Order Shipping',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_order_total',
    'label' => 'Before Order Total',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_total',
    'label' => 'After Order Total',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_payment_information',
    'label' => 'Before Payment Information',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'before_place_order_button',
    'label' => 'Before Place Order Button',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_place_order_button',
    'label' => 'After Place Order Button',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_payment',
    'label' => 'After Order Payment',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_order_review',
    'label' => 'After Order Review',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
  array(
    'uid' => 'after_checkout_form',
    'label' => 'After Checkout Form',
    'helper' => '',
    'supplemental' => '',
    'section' => 'checkout_page_tab',
    'type' => 'textarea',
    'placeholder'	=> __( '' ),
    'default' => '',
    'rows' => '3',
  ),
);
foreach( $fields as $field ){
    add_settings_field( $field['uid'], $field['label'], array( $this, 'field_callback' ), 'checkout_page_tab', $field['section'], $field );
    register_setting( 'checkout_page_tab', $field['uid'] );
}