<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}
$strings = array(
  array(
    'wooHook' => 'woocommerce_before_checkout_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-announcements',
    'hooky_content' => get_option('before_woo_announcements'),
  ),
  array(
    'wooHook' => 'woocommerce_checkout_before_customer_details',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-announcements',
    'hooky_content' => get_option('after_woo_announcements'),
  ),
  array(
    'wooHook' => 'woocommerce_before_checkout_billing_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-billing',
    'hooky_content' => get_option('before_billing_information'),
  ),
  array(
    'wooHook' => 'woocommerce_after_checkout_billing_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-billing',
    'hooky_content' => get_option('after_billing_information'),
  ),
  array(
    'wooHook' => 'woocommerce_before_checkout_shipping_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-shipping',
    'hooky_content' => get_option('before_shipping_information'),
  ),
  array(
    'wooHook' => 'woocommerce_after_checkout_shipping_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-shipping',
    'hooky_content' => get_option('after_shipping_information'),
  ),
  array(
    'wooHook' => 'woocommerce_after_order_notes',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-notes',
    'hooky_content' => get_option('after_order_notes'),
  ),
  array(
    'wooHook' => 'woocommerce_checkout_after_customer_details',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-customer-details',
    'hooky_content' => get_option('after_customer_details'),
  ),
  array(
    'wooHook' => 'woocommerce_checkout_before_order_review',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-order-review',
    'hooky_content' => get_option('before_order_review'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_before_cart_contents',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-before-cart-contents',
    'hooky_content' => get_option('before_cart_contents'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_after_cart_contents',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-after-cart-contents',
    'hooky_content' => get_option('after_order_cart_contents'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_before_shipping',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-before-shipping-contents',
    'hooky_content' => get_option('before_order_shipping_contents'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_after_shipping',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-after-shipping-contents',
    'hooky_content' => get_option('after_order_shipping_contents'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_before_order_total',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-before-order-total',
    'hooky_content' => get_option('before_order_total'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_after_order_total',
    'priority' => '10',
    'elem_start' => 'tr><td colspan="2" ',
    'elem_end' => '</td></tr>',
    'elem_class' => 'mcw-after-order-total',
    'hooky_content' => get_option('after_order_total'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_before_payment',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-payment-info',
    'hooky_content' => get_option('before_payment_information'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_before_submit',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-before-place-order',
    'hooky_content' => get_option('before_place_order_button'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_after_submit',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-place-order',
    'hooky_content' => get_option('after_place_order_button'),
  ),
  array(
    'wooHook' => 'woocommerce_review_order_after_payment',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-order-payment',
    'hooky_content' => get_option('after_order_payment'),
  ),
  array(
    'wooHook' => 'woocommerce_checkout_after_order_review',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-order-review',
    'hooky_content' => get_option('after_order_review'),
  ),
  array(
    'wooHook' => 'woocommerce_after_checkout_form',
    'priority' => '10',
    'elem_start' => 'div',
    'elem_end' => '</div>',
    'elem_class' => 'mcw-after-checkout-form',
    'hooky_content' => get_option('after_checkout_form'),
  ),

);
require_once( 'loop-classes.php' );
$checkout_loop = new Hooky_Action_Hook_Loop_Class( $strings );